version: "3.9"

services:
  backend:
    image: chat-backend:1.0
    container_name: chat-backend
    ports:
      - "5001:5001"

  frontend:
    build: ./frontend
    container_name: chat-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

